### ISSUE TITLE
Improve log output while parsing log files

### ISSUE THREAD

**Issue by cho-trackman** [cake-contrib/Cake.Issues.MsBuild#200]
I spend a long time debugging why `Issues` didn't have the correct paths set. It turns out that using a logger where the verbosity is set to `Quiet` does not contain the `<project...` element that contains the project path. The issue is that `XmlFileLoggerLogFileFormat` [is silent about it](https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/1a97adf23c759fa9f9f5444a8ab1e70d71c21399/src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs#L201) and you have to debug a lot to discover it.

I suggest adding a disclaimer somewhere or make `XmlFileLoggerLogFileFormat` throw. What do you think?

**Comment by phlorian** [comment]
Throwing an exception is wrong in this case, as the tool should be as stable as possible. In this case, logging a message on level "Verbose" is the right way. Not only for TryGetProject, but should be implemented for the whole parser.

Are you in a position to provide a pull request for this?

**Comment by cho-trackman** [comment]
I can do that. But I do feel verbose is a too low log level.

**Comment by phlorian** [comment]
I discussed this with @pascalberger. A higher log level should be used carefully as this quickly leads to a lot of messages. At the line you mentioned a "Information" log level could be used. But then you still do not know why the project does not exist. So the next step would be to add a verbose logging, to find out why that project is not present.

**Comment by pascalberger** [comment]
@cho-trackman You still plan to work on this?

**Comment by cho-trackman** [comment]
Nah, I'm not really sure what to put in the code for this one. But I will work on the binary logger today.

**Comment by pascalberger** [comment]
@cho-trackman OK, I can take this.

For the binary logger I created already two PRs: https://github.com/cake-contrib/Cake.Issues.MsBuild/pull/204, https://github.com/cake-contrib/Cake.Issues.MsBuild/pull/205

**Comment by cho-trackman** [comment]
@pascalberger Oh, nice.
Sorry I was too slow, got caught up by a hotfix.

**Comment by pascalberger** [comment]
> @cho-trackman wrote:
> Nah, I'm not really sure what to put in the code for this one. But I will work on the binary logger today.

See #206 for an implementation. Does this work for you?

**Comment by cho-trackman** [comment]
@

> > @cho-trackman wrote:
> > Nah, I'm not really sure what to put in the code for this one. But I will work on the binary logger today.
> 
> See #206 for an implementation. Does this work for you?

Perfect! Thanks for doing this.
