### ISSUE TITLE
Parse errors from log files

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.MsBuild#201]
Parse errors from log files in `MsBuildBinaryLogFileFormat` and `MsBuildXmlFileLoggerFormat`

- [x] Support parsing of errors in MsBuildXmlFileLoggerFormat (GH-199)
- [ ] Support parsing of errors in MsBuildBinaryLogFileFormat (GH-205)
- [ ] Update feature documentation (GH-204)

**Comment by cho-trackman** [comment]
Other than the `.WithPriority(IssuePriority.Warning)` part, where does the `MsBuildBinaryLogFileFormat` only handle warnings?

**Comment by pascalberger** [comment]
> @cho-trackman wrote:
> Other than the `.WithPriority(IssuePriority.Warning)` part, where does the `MsBuildBinaryLogFileFormat` only handle warnings?

It's the cast on https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/develop/src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs#L46. Unfortunately `BuildWarningEventArgs` and `BuildErrorEventArgs` don't share a common ancestor, so code needs to be duplicated. Are you interested in providing a PR for this too?

**Comment by cho-trackman** [comment]
Yes, I can do that.

I'm also planning on a PR for updating the [docs](https://github.com/cho-trackman/Cake.Issues.PullRequests.AzureDevOps/blob/develop/docs/examples/azure-pipelines.md) to provide a more up-to-date and "full" sample.

**Comment by pascalberger** [comment]
> I'm also planning on a PR for updating the [docs](https://github.com/cake-contrib/Cake.Issues.PullRequests.AzureDevOps/blob/develop/docs/examples/azure-pipelines.md) to provide a more up-to-date and "full" sample.

Updating docs for this issue would only require to update [Features](https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/develop/docs/features.md) (`Basic features` mentiones that warnings are read; `Supported IIssue properties` needs to be updated for the priority fields).

We're definitely open to improve other documentation and examples, but this would be something outside the scope of this issue. Please notes that examples for the individual addins on purpose only show specific aspects (e.g. [Using with Azure Pipelines](https://cakeissues.net/docs/pull-request-systems/azure-devops/examples/azure-pipelines) shows how to integrate with Azure Repos pull requests when using Azure Pipelines) and didn't wan't to clutter them with additional code. Which aspect are you missing in the mentioned example?
