### ISSUE TITLE
Issue with Publish Method for Transform file

### ISSUE THREAD

**Issue by Avinchandsanaya** [cake-contrib/Cake.Issues.MsBuild#264]
I am having an issue with the cake publish method. We have lots of transform files and want those to be published when we trigger publish method. But it is always picking the AccessResultCacheTuning**.config** not picking AccessResultCacheTuning.**Release.config** . 

Here are the details of Publish method with arguments. 

### public void PublishProjects(string rootFolder, string publishRoot)
{
  Func<IFileSystemInfo, bool> excludes = fileSystemInfo => !fileSystemInfo.Path.FullPath.Contains("CRM");

  var projects = GetFiles($"{rootFolder}\\**\\code\\*.csproj", excludes);
  Information("Publishing " + rootFolder + " to " + publishRoot);
  foreach (var project in projects) {
  Information("project Name " + project);
    MSBuild(project, cfg => InitializeMSBuildSettingsInternal(cfg)
      .WithTarget(configuration.BuildTargets)
      .WithProperty("DeployOnBuild", "true")
      .WithProperty("DeployDefaultTarget", "WebPublish")
      .WithProperty("WebPublishMethod", "FileSystem")
      .WithProperty("DeleteExistingFiles", "false")
      .WithProperty("publishUrl", publishRoot)
      .WithProperty("BuildProjectReferences", "false")
	  .WithProperty("LastUsedBuildConfiguration", "Release")
	  .WithProperty("LastUsedPlatform", "Any CPU")
      );
  }
}

**Comment by pascalberger** [comment]
@Avinchandsanaya This is the repository for the MsBuild output parser addin. For general help about Cake you should start a new discussion in the main Cake repository: https://github.com/orgs/cake-build/discussions
