### ISSUE TITLE
DotNetCore[Build|Publish] Support

### ISSUE THREAD

**Issue by dustinchilson** [cake-contrib/Cake.Issues.MsBuild#51]
In my Build script I'm attempting to do this to generate the build output for the Issue tool. 

```
DotNetCorePublish(".", new DotNetCorePublishSettings
        {
            Configuration = configuration,
            NoRestore = true,
            MSBuildSettings = new DotNetCoreMSBuildSettings()
                .WithLogger(
                    Context.Tools.Resolve("MSBuild.ExtensionPack.Loggers.dll").FullPath,
                    "XmlFileLogger",
                    $"logfile=\"{msBuildLogFile}\";verbosity=Detailed;encoding=UTF-8"
                )
        });
```

This does not work as the MSBuild.ExtensionPack.Loggers.dll doesn't work in the dotnet core msbuild Per https://github.com/Microsoft/msbuild/issues/2111.

Is there a work around? I see #38 which might also work but doesn't seem to be an active case.

**Comment by pascalberger** [comment]
You can check out version 0.6.1-beta0002 which contains support for binary logs. 

To use binary logs (proper documentation will follow once officially released):

```csharp
#addin "Cake.Issues.MsBuild&prerelease"

var settings = new MSBuildSettings();
settings.BinaryLogger =
    new MSBuildBinaryLogSettings() 
    { 
        Enabled = true, 
        FileName = @"c:\repo\output.binlog" 
    };
MSBuild(@"c:\repo\mysolution.sln", settings);

var settings =
    new ReadIssuesSettings(@"c:\repo")
    {
        Format = IssueCommentFormat.Markdown
    };

var issues =
    ReadIssues(
        MsBuildIssuesFromFilePath(
            @"c:\repo\output.binlog",
            MsBuildBinaryLogFileFormat)
        settings));
``` 

Please not that binary logs contain the whole environment including all environment variables, which might be a security concern. 

If binary logs don't work for you, it's quite easy to implement support for any other logger to Cake.Issues.MsBuild as long as the generated output is in any machine readable form.

Please let me know if the binary logs work for you and I can do a proper release containing support for it.

**Comment by pascalberger** [comment]
@dustinchilson [Version 0.6.1](https://www.nuget.org/packages/Cake.Issues.MsBuild/0.6.1) with support for binary logger has been released.
