### ISSUE TITLE
Support MsBuild new location

### ISSUE THREAD

**Issue by VladislavAntonyuk** [cake-contrib/Cake.Issues.MsBuild#73]
MSBuild
The MSBuild toolset version has been changed from 15.0 to Current. MSBuild.exe is now in %VSINSTALLDIR%\MSBuild\Current\Bin\MSBuild.exe.
MSBuild (and Visual Studio) now targets .NET Framework 4.7.2. If you wish to use new MSBuild API features, your assembly must also upgrade, but existing code will continue to work.

**Comment by pascalberger** [comment]
@VladislavAntonyuk This addin doesn't use MsBuild.exe it just parses MsBuild logfiles. How is the change you mentioned affecting this addin?

**Comment by VladislavAntonyuk** [comment]
it should be in Cake.Msbuild. Closed

**Comment by pascalberger** [comment]
@VladislavAntonyuk There's no Cake.Msbuild AFAIK. The `MsBuild` alias is part of Cake itself. So https://github.com/cake-build/cake would be the correct repository.
