### ISSUE TITLE
Migrate to .NET Core

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.MsBuild#8]
Addin should support .NET Core and Cake CoreCLR runner

**Comment by t-johnson** [comment]
i am taking this one

**Comment by t-johnson** [comment]
@pascalberger  Sorry for the multiple commits on this one - i had started the work the branch before i saw your suggestion of making a feature branch off my 'develop'.

**Comment by pascalberger** [comment]
@t-johnson Thanks for your effort 👍 And don't worry about the commits. I'll squash them before I merge the PR
