### ISSUE TITLE
Create avenue for financial contributions for project

### ISSUE THREAD

**Issue by brianfeucht** [cake-contrib/Cake.Issues.MsBuild#85]
I'd love to buy you a 🍺 

Several other projects I've worked with use [Open Collective](https://opencollective.com/), but I'd be willing to contribute a bit financially to any way that works for you

**Comment by pascalberger** [comment]
@brianfeucht Really, really appreciate this 👍 As a maintainer it means a lot to have people saying thank you, which don't happens that often. 

As I'm in the lucky position to not depend on any financial contributions setting up something like open collective doesn't make much sense in my case as it won't have any impact on the project and your issue already means a lot to me.
If you want you can contribute to the [.NET Foundation](https://opencollective.com/dotnetfdncollective) which supports open source projects in the .NET ecosystem and where Cake is also part of. I think donations have a bigger impact there than if I setup something here for myself.

**Comment by pascalberger** [comment]
The Cake project now also has the possibility for financial support: https://opencollective.com/cake
